### ISSUE TITLE
Allow layers to mix data sources

### ISSUE THREAD

**Issue by miniwark** [widestage/widestage#24]
Actually a layer is bind to a data source. It is not possible to get a table from a source and join it with another table from another source. When adding a new table in a layer, the modal dialog did not allow to change the data source.

**Comment by beevou** [comment]
A layer belongs only to one datasource because when generating SQL queries on the fly you can't mixup in a select tables from one datasource ie. Postgres and tables from other datasource i.e MySQL, the resulting SQL will fail, this behaviour of the semantic layer is the same for all reporting tools with semantic layers like BO or Microstrategy, there is a solution for this creating two separate queries and mixup (join) those results in the widestage backend, but the performance will be very poor and will consume a lot of the system resources probably resulting in denying the service for the rest of the users.
