### ISSUE TITLE
Can't connect to Oracle DB 

### ISSUE THREAD

**Issue by cchung26** [widestage/widestage#39]
I've selected Oracle as a data source and trying to configure it.
I see that Widestage is throwing an error message after I test the connection.
The error I am getting is "Error: cannot find module 'jdbc'"
I see that ojdbc7.jar and orai18n.jar files exist in /widestage/server/jdbc/oracle folder
I pulled the current version of Widestage on 11 May 2017 ( a89a408 )

Any ideas? Thanks.

**Comment by beevou** [comment]
We have removed the Oracle JDBC connection as there are some problems with the numeric values, and back to the native oracle connection, to enable that first you need to install the nodejs oracle library that is not included in our default npm package , be sure to have installed the Oracle Instant client before that otherwise you will get an npm error (https://github.com/oracle/node-oracledb), after that then you can just start the WST server and choose oracle as a connection.
